# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
  S3_BUCKET_NAME: achieve-berkeley
  AWS_ACCESS_KEY_ID: AKIAIZPW7MANJUBPXN5Q
  AWS_SECRET_ACCESS_KEY: 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

production:
  S3_BUCKET_NAME: achieve-berkeley
  AWS_ACCESS_KEY_ID: AKIAIZPW7MANJUBPXN5Q
  AWS_SECRET_ACCESS_KEY: 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
